import React, { useState } from 'react';
import { twMerge } from 'tailwind-merge';
import { Sparkles, Bot, Code2 } from 'lucide-react';
import AIForm from '../components/ai-form/AIForm';
import type { FormField } from '../components/ai-form/FormFields';

// --- Simulation Data ---
export type FormData = Record<string, any>;

// 表单配置类型定义
export type FormSchema = {
  title: string;
  fields: FormField[];
  submitLabel?: string;
};

const PROJECT_MANAGEMENT_SCHEMA: FormSchema = {
  title: '项目任务管理',
  fields: [
    {
      key: 'title',
      label: 'Task Title',
      type: 'text',
      description: 'A concise name for the task.',
      options: ['Fix login bug', 'Update landing page', 'Refactor API', 'Write documentation'],
      required: true,
    },
    {
      key: 'priority',
      label: 'Priority',
      type: 'select',
      description: 'How urgent is this task?',
      options: ['Low', 'Medium', 'High', 'Critical'],
      creatable: false,
    },
    {
      key: 'assignees',
      label: 'Assignees',
      type: 'tags',
      description: 'Who is responsible for this.',
      options: ['Alice', 'Bob', 'Charlie', 'Dave', 'Eve'],
    },
    {
      key: 'tags',
      label: 'Labels',
      type: 'tags',
      description: 'Categorize this task.',
      options: ['Bug', 'Feature', 'Documentation', 'Design', 'Backend', 'Frontend'],
    }
  ],
  submitLabel: '创建任务'
};

const EVENT_PLANNING_SCHEMA: FormSchema = {
  title: '活动策划',
  fields: [
    {
      key: 'eventName',
      label: 'Event Name',
      type: 'text',
      options: ['Team Building', 'Quarterly Review', 'Product Launch', 'Holiday Party'],
      required: true,
    },
    {
      key: 'venue',
      label: 'Venue Type',
      type: 'select',
      options: ['Office HQ', 'Virtual (Zoom)', 'Conference Center', 'Restaurant'],
      creatable: true,
    },
    {
      key: 'requirements',
      label: 'Requirements',
      type: 'tags',
      options: ['Catering', 'Projector', 'Sound System', 'Swag Bags', 'Recording'],
    }
  ],
  submitLabel: '策划活动'
};

const PROGRAMMING_QUIZ_SCHEMA: FormSchema = {"title":"编程语言知识小测验","fields":[{"key":"language","label":"您想了解的编程语言","description":"例如：Python, JavaScript, Java, C++ 等","required":true,"type":"select","options":["Python","JavaScript","Java","C++","Go","Rust","Swift"]},{"key":"topic","label":"您想了解的具体主题","description":"例如：数据结构、算法、网络编程等","required":true,"type":"select","options":["数据结构","算法","网络编程","并发编程","机器学习","前端开发"]},{"key":"difficulty","label":"您希望小测验的难度","description":"请选择一个难度等级","required":true,"type":"select","options":["初学者","中级","高级"]}],"submitLabel":"生成小测验"};

const AIFormDemoPage: React.FC = () => {
  const [currentSchema, setCurrentSchema] = useState<FormSchema>(PROJECT_MANAGEMENT_SCHEMA);
  const [formData, setFormData] = useState<FormData>({});
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeScenario, setActiveScenario] = useState<'project' | 'event' | 'quiz'>('project');
  const [lastSubmitted, setLastSubmitted] = useState<FormData | null>(null);

  const simulateAIGeneration = (scenario: 'project' | 'event' | 'quiz') => {
    setIsGenerating(true);
    setLastSubmitted(null);
    setFormData({}); // clear form
    
    // Simulate network delay
    setTimeout(() => {
      if (scenario === 'project') {
        setCurrentSchema(PROJECT_MANAGEMENT_SCHEMA);
      } else if (scenario === 'event') {
        setCurrentSchema(EVENT_PLANNING_SCHEMA);
      } else {
        setCurrentSchema(PROGRAMMING_QUIZ_SCHEMA);
      }
      setActiveScenario(scenario);
      setIsGenerating(false);
    }, 200);
  };

  const handleSubmit = (data: FormData) => {
    console.log("Form Submitted:", data);
    setLastSubmitted(data);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
          <Bot className="w-8 h-8 text-indigo-600" />
          GenUI Form Generator
        </h1>
        <p className="mt-2 text-slate-600">
          This demo simulates an application where the form structure is dynamically generated by an AI model based on user context. 
          The UI components are optimized for rapid data entry with smart suggestions.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column: Controls & Context */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-white p-2 rounded-xl shadow-sm border border-slate-200">
            <h2 className="text-sm font-semibold text-slate-900 uppercase tracking-wider mb-4 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-amber-500" />
              Simulate AI Context
            </h2>
            <div className="space-y-1">
              <button
                onClick={() => simulateAIGeneration('project')}
                disabled={isGenerating}
                className={twMerge(
                  "w-full text-left px-4 py-3 rounded-lg border transition-all relative overflow-hidden",
                  activeScenario === 'project' 
                    ? "bg-indigo-50 border-indigo-200 ring-1 ring-indigo-500" 
                    : "bg-white border-slate-200 hover:border-indigo-300 hover:shadow-sm"
                )}
              >
                <div className="flex justify-between items-center mb-1">
                  <span className="font-medium text-slate-900">{PROJECT_MANAGEMENT_SCHEMA.title}</span>
                  {activeScenario === 'project' && !isGenerating && <span className="text-xs bg-indigo-200 text-indigo-800 px-2 py-0.5 rounded-full">Active</span>}
                </div>
                <p className="text-xs text-slate-500">Generates fields for tracking engineering tasks.</p>
              </button>

              <button
                onClick={() => simulateAIGeneration('event')}
                disabled={isGenerating}
                className={twMerge(
                  "w-full text-left px-4 py-3 rounded-lg border transition-all relative overflow-hidden",
                  activeScenario === 'event' 
                    ? "bg-indigo-50 border-indigo-200 ring-1 ring-indigo-500" 
                    : "bg-white border-slate-200 hover:border-indigo-300 hover:shadow-sm"
                )}
              >
                 <div className="flex justify-between items-center mb-1">
                  <span className="font-medium text-slate-900">{EVENT_PLANNING_SCHEMA.title}</span>
                  {activeScenario === 'event' && !isGenerating && <span className="text-xs bg-indigo-200 text-indigo-800 px-2 py-0.5 rounded-full">Active</span>}
                </div>
                <p className="text-xs text-slate-500">Generates fields for organizing company events.</p>
              </button>

              <button
                onClick={() => simulateAIGeneration('quiz')}
                disabled={isGenerating}
                className={twMerge(
                  "w-full text-left px-4 py-3 rounded-lg border transition-all relative overflow-hidden",
                  activeScenario === 'quiz' 
                    ? "bg-indigo-50 border-indigo-200 ring-1 ring-indigo-500" 
                    : "bg-white border-slate-200 hover:border-indigo-300 hover:shadow-sm"
                )}
              >
                 <div className="flex justify-between items-center mb-1">
                  <span className="font-medium text-slate-900">{PROGRAMMING_QUIZ_SCHEMA.title}</span>
                  {activeScenario === 'quiz' && !isGenerating && <span className="text-xs bg-indigo-200 text-indigo-800 px-2 py-0.5 rounded-full">Active</span>}
                </div>
                <p className="text-xs text-slate-500">生成编程语言知识小测验表单</p>
              </button>
            </div>
            
            <div className='mt-4'>

              <AIForm fields={[
                { key: 'prompt', type: 'text', options: ['Bug Report', 'Customer Feedback', 'Event Registration']}
              ]} />
            </div>
          </div>

          {/* Real-time Data Preview */}
          <div className="bg-slate-900 rounded-xl p-5 shadow-lg text-slate-300 font-mono text-xs overflow-hidden">
             <div className="flex items-center gap-2 mb-3 text-slate-400 border-b border-slate-700 pb-2">
               <Code2 className="w-4 h-4" />
               <span>Live Data State</span>
             </div>
             <pre className="overflow-auto max-h-60 custom-scrollbar">
               {JSON.stringify(formData, null, 2)}
             </pre>
          </div>
        </div>

        {/* Right Column: The AI Form */}
        <div className="lg:col-span-8">
           <AIForm 
              key={currentSchema.title}
              title={currentSchema.title}
              fields={currentSchema.fields} 
              autoPickValue
              isGenerating={isGenerating}
              onChange={setFormData}
              onSubmit={handleSubmit}
              submitLabel={currentSchema.submitLabel}
           />

           {lastSubmitted && (
             <div className="mt-6 p-4 bg-emerald-50 border border-emerald-200 rounded-lg animate-fade-in">
                <h3 className="text-emerald-800 font-semibold mb-2">Submission Successful</h3>
                <p className="text-emerald-700 text-sm">
                  The data was successfully captured. In a real app, this payload would be sent to your backend.
                </p>
             </div>
           )}
        </div>

      </div>
    </div>
  );
};

export default AIFormDemoPage;